import { useState, useEffect, useCallback } from 'react';
import { useDashboard } from '@/lib/dashboardContext';
import { Cloud, Sun, CloudRain, Snowflake, CloudSun, MapPin, RefreshCw, Droplets } from 'lucide-react';

function getGreeting(name?: string) { const h = new Date().getHours(); let g = 'Good Night'; if (h >= 5 && h < 12) g = 'Good Morning'; else if (h >= 12 && h < 17) g = 'Good Afternoon'; else if (h >= 17 && h < 21) g = 'Good Evening'; return name ? `${g}, ${name}` : g; }
function formatDate() { return new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }); }
const WEATHER_CODES: Record<number, string> = {0:'Clear',1:'Mainly Clear',2:'Partly Cloudy',3:'Overcast',45:'Fog',48:'Fog',51:'Drizzle',53:'Drizzle',55:'Drizzle',61:'Rain',63:'Rain',65:'Heavy Rain',71:'Snow',73:'Snow',75:'Heavy Snow',80:'Rain Showers',81:'Rain Showers',82:'Heavy Showers',95:'Thunderstorm',96:'Thunderstorm',99:'Thunderstorm'};
const WeatherIcon = ({ condition }: { condition: string }) => { const cls = 'w-7 h-7'; const c = condition.toLowerCase(); if (c.includes('rain') || c.includes('drizzle') || c.includes('shower') || c.includes('thunder')) return <CloudRain className={cls} />; if (c.includes('snow')) return <Snowflake className={cls} />; if (c.includes('cloud') || c.includes('overcast') || c.includes('fog')) return <Cloud className={cls} />; if (c.includes('partly') || c.includes('mainly')) return <CloudSun className={cls} />; return <Sun className={cls} />; };
interface WeatherData { temp: number; condition: string; humidity: number; city: string; }
function DotClock({ time }: { time: Date }) { const hours = time.getHours(); const mins = time.getMinutes(); const h12 = hours % 12 || 12; const ampm = hours >= 12 ? 'PM' : 'AM'; const timeStr = `${h12.toString().padStart(2, '0')}:${mins.toString().padStart(2, '0')}`; const [colonVisible, setColonVisible] = useState(true); useEffect(() => { const t = setInterval(() => setColonVisible(v => !v), 1000); return () => clearInterval(t); }, []); return <div className="flex items-baseline gap-0.5 mt-2"><div className="flex items-baseline" style={{ fontFamily: "'Courier New', 'SF Mono', monospace", letterSpacing: '0.15em' }}>{timeStr.split('').map((char, i) => <span key={i} className="glass-text font-light" style={{ fontSize: '2rem', lineHeight: 1, opacity: char === ':' ? (colonVisible ? 0.9 : 0.2) : 0.9, transition: 'opacity 0.3s ease', textShadow: '0 0 8px rgba(255,255,255,0.15)' }}>{char}</span>)}</div><span className="glass-text-subtle text-xs font-medium ml-1" style={{ letterSpacing: '0.1em' }}>{ampm}</span></div>; }
async function getCoordinates(city: string, state: string): Promise<{ latitude: number; longitude: number; name: string } | null> { const url = `https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=10&language=en&format=json&countryCode=IN`; const res = await fetch(url); if (!res.ok) return null; const data = await res.json(); const results = Array.isArray(data.results) ? data.results : []; const stateLower = state.toLowerCase(); const exact = results.find((r: any) => String(r.name || '').toLowerCase() === city.toLowerCase() && String(r.admin1 || '').toLowerCase().includes(stateLower)); const sameState = results.find((r: any) => String(r.admin1 || '').toLowerCase().includes(stateLower)); const chosen = exact || sameState || results[0]; return chosen ? { latitude: chosen.latitude, longitude: chosen.longitude, name: chosen.name || city } : null; }

export default function DashboardHeader() {
  const { settings } = useDashboard();
  const [weather, setWeather] = useState<WeatherData | null>(null);
  const [loading, setLoading] = useState(false);
  const [time, setTime] = useState(new Date());
  useEffect(() => { const timer = setInterval(() => setTime(new Date()), 1000); return () => clearInterval(timer); }, []);
  const fetchWeather = useCallback(async () => { setLoading(true); try { const city = settings.selectedCity || 'Chennai'; const state = settings.selectedState || 'Tamil Nadu'; const coordinates = await getCoordinates(city, state); if (!coordinates) throw new Error('Location not found'); const url = `https://api.open-meteo.com/v1/forecast?latitude=${coordinates.latitude}&longitude=${coordinates.longitude}&current=temperature_2m,relative_humidity_2m,weather_code&timezone=auto`; const res = await fetch(url); if (!res.ok) throw new Error('Weather failed'); const data = await res.json(); const current = data.current; if (!current) throw new Error('Current weather missing'); const code = Number(current.weather_code ?? 0); setWeather({ temp: Math.round(Number(current.temperature_2m)), condition: WEATHER_CODES[code] || 'Clear', humidity: Math.round(Number(current.relative_humidity_2m)), city: coordinates.name || city }); } catch { setWeather({ temp: 28, condition: 'Partly Cloudy', humidity: 65, city: settings.selectedCity || 'Chennai' }); } finally { setLoading(false); } }, [settings.selectedCity, settings.selectedState]);
  useEffect(() => { fetchWeather(); const pollMs = Math.max(settings.syncInterval || 30, 5) * 60000; const interval = setInterval(fetchWeather, pollMs); const sync = () => fetchWeather(); window.addEventListener('mady:sync-now', sync); return () => { clearInterval(interval); window.removeEventListener('mady:sync-now', sync); }; }, [fetchWeather, settings.syncInterval]);
  return <header className="px-5 pt-6 pb-2 w-full"><div className="flex gap-3 w-full" style={{ alignItems: 'stretch' }}><div className="glass-panel p-4 flex flex-col justify-between" style={{ flex: 3, minWidth: 0 }}><div><h1 className="text-xl font-semibold glass-text tracking-tight text-left truncate">{getGreeting(settings.userName || undefined)}</h1><p className="text-xs glass-text-subtle mt-0.5 text-left">{formatDate()}</p></div><DotClock time={time} /></div>{settings.showWeather && <div className="glass-panel p-3 flex flex-col items-center justify-center gap-1.5" style={{ flex: 1.5, minWidth: 0 }}><WeatherIcon condition={weather?.condition || 'Clear'} /><div className="text-center"><div className="glass-text text-2xl font-light leading-tight">{weather ? `${weather.temp}°` : '...'}</div><div className="glass-text-subtle text-[10px] leading-tight mt-0.5">{weather?.condition || 'Loading'}</div></div><div className="flex items-center gap-1 max-w-full"><MapPin className="w-2.5 h-2.5 glass-text-subtle shrink-0" /><span className="glass-text-subtle text-[9px] truncate">{weather?.city || settings.selectedCity}</span></div><div className="flex items-center gap-2">{weather && <div className="flex items-center gap-0.5"><Droplets className="w-2.5 h-2.5 glass-text-subtle" /><span className="glass-text-subtle text-[9px]">{weather.humidity}%</span></div>}<button onClick={fetchWeather} className="tap-scale" disabled={loading}><RefreshCw className={`w-3 h-3 glass-text-subtle ${loading ? 'animate-spin' : ''}`} /></button></div></div>}</div></header>;
}
