import { useState, useRef } from 'react';
import { Settings, X, Image, ChevronDown, ChevronUp, RefreshCw, MapPin, Palette, User, Eye, Newspaper, Download, Upload, Trash2 } from 'lucide-react';
import { useDashboard, GlassStyle, NEWS_GENRES, NewsGenre } from '@/lib/dashboardContext';
import { INDIAN_LOCATIONS } from '@/lib/locations';
import { assetPath } from '@/lib/assets';

const WALLPAPERS = [
  { name: 'Nordic', src: assetPath('images/wallpaper-nordic.jpg') },
  { name: 'Dark', src: assetPath('images/wallpaper-dark.jpg') },
  { name: 'Sunset', src: assetPath('images/wallpaper-sunset.jpg') },
  { name: 'Minimal', src: assetPath('images/wallpaper-minimal.jpg') },
  { name: 'Pixel Night', src: assetPath('images/wallpaper-pixel-night.jpg') },
  { name: 'Pixel Day', src: assetPath('images/wallpaper-pixel-day.jpg') },
  { name: 'Aurora', src: assetPath('images/wallpaper-aurora.jpg') },
  { name: 'Mountains', src: assetPath('images/wallpaper-mountains.jpg') },
];

const GLASS_STYLES: { id: GlassStyle; name: string; desc: string }[] = [
  { id: 'acrylic', name: 'Acrylic', desc: 'Frosted, soft blur' },
  { id: 'liquid-glass', name: 'Liquid Glass', desc: 'Deep blur, crisp edges' },
  { id: 'clear', name: 'Clear', desc: 'Minimal, transparent' },
  { id: 'translucent', name: 'Translucent', desc: 'Dense, matte feel' },
];

function Slider({ label, value, min, max, step, onChange }: { label: string; value: number; min: number; max: number; step: number; onChange: (v: number) => void }) {
  return <label className="flex flex-col gap-1.5"><div className="flex justify-between"><span className="glass-text text-xs">{label}</span><span className="glass-text-subtle text-xs">{value}</span></div><input type="range" min={min} max={max} step={step} value={value} onChange={e => onChange(parseFloat(e.target.value))} className="w-full h-1 bg-white/20 rounded-full appearance-none cursor-pointer [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-4 [&::-webkit-slider-thumb]:h-4 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-white [&::-webkit-slider-thumb]:shadow-md" /></label>;
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (v: boolean) => void }) {
  return <label className="flex items-center justify-between cursor-pointer"><span className="glass-text text-xs">{label}</span><button type="button" className={`w-10 h-5 rounded-full transition-colors duration-200 relative ${checked ? 'bg-white/40' : 'bg-white/10'}`} onClick={() => onChange(!checked)}><span className="absolute top-0.5 left-0 w-4 h-4 rounded-full bg-white shadow transition-transform duration-200" style={{ transform: checked ? 'translateX(20px)' : 'translateX(2px)' }} /></button></label>;
}

function Section({ id, section, title, icon, setSection, children }: { id: string; section: string | null; title: string; icon?: React.ReactNode; setSection: (s: string) => void; children: React.ReactNode }) {
  const open = section === id;
  return <div className="glass-panel overflow-hidden"><button onClick={() => setSection(id)} className="w-full flex items-center justify-between p-3"><span className="glass-text text-sm font-medium flex items-center gap-2">{icon}{title}</span>{open ? <ChevronUp className="w-4 h-4 glass-text-subtle" /> : <ChevronDown className="w-4 h-4 glass-text-subtle" />}</button>{open && <div className="px-3 pb-3 space-y-3">{children}</div>}</div>;
}

export default function SettingsPanel() {
  const { settings, updateSettings, applyGlassStyle, settingsOpen, setSettingsOpen, clearSearchHistory, exportConfig, importConfig } = useDashboard();
  const [section, setSectionRaw] = useState<string | null>('appearance');
  const [status, setStatus] = useState('');
  const fileRef = useRef<HTMLInputElement>(null);
  const importRef = useRef<HTMLInputElement>(null);
  const selectedLocation = INDIAN_LOCATIONS.find(l => l.state === settings.selectedState);
  const cities = selectedLocation?.cities || [];
  const setSection = (s: string) => setSectionRaw(prev => prev === s ? null : s);

  const handleUpload = (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => updateSettings({ customWallpaper: reader.result as string, wallpaper: reader.result as string }); reader.readAsDataURL(file); e.target.value = ''; };
  const handleExport = () => { const blob = new Blob([JSON.stringify(exportConfig(), null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `mady-config-${new Date().toISOString().slice(0, 10)}.json`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); setStatus('Config exported'); };
  const handleImport = async (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; try { await importConfig(JSON.parse(await file.text())); setStatus('Config imported successfully'); } catch { setStatus('Import failed: choose a valid Mady config JSON'); } finally { e.target.value = ''; } };
  const handleSyncNow = () => { window.dispatchEvent(new CustomEvent('mady:sync-now')); setStatus('Refreshing weather and news'); };

  return <><button onClick={() => setSettingsOpen(true)} className="fixed bottom-6 right-6 z-40 glass-panel w-12 h-12 flex items-center justify-center tap-scale shadow-lg" style={{ borderRadius: '50%' }}><Settings className="w-5 h-5 glass-text" /></button>{settingsOpen && <div className="fixed inset-0 z-50" onClick={() => setSettingsOpen(false)}><div className="absolute inset-0 bg-black/30 backdrop-blur-sm" /><div className="absolute bottom-0 left-0 right-0 max-h-[85vh] overflow-y-auto glass-panel animate-slide-up" style={{ borderBottomLeftRadius: 0, borderBottomRightRadius: 0 }} onClick={e => e.stopPropagation()}><div className="flex justify-center pt-3 pb-1"><div className="w-10 h-1 rounded-full bg-white/30" /></div><div className="flex items-center justify-between px-5 pb-3"><h2 className="glass-text font-semibold text-lg">Settings</h2><button onClick={() => setSettingsOpen(false)} className="tap-scale"><X className="w-5 h-5 glass-text-subtle" /></button></div><div className="px-5 pb-8 space-y-2">
    <Section id="profile" section={section} setSection={setSection} title="Profile" icon={<User className="w-4 h-4" />}><label className="glass-text text-xs block">Your Name</label><input type="text" value={settings.userName} onChange={e => updateSettings({ userName: e.target.value })} placeholder="Enter your name" className="w-full bg-white/10 rounded-lg px-3 py-2 glass-text text-sm outline-none placeholder:text-white/30" /></Section>
    <Section id="location" section={section} setSection={setSection} title="Location" icon={<MapPin className="w-4 h-4" />}><label className="glass-text text-xs block">State</label><select value={settings.selectedState} onChange={e => { const state = e.target.value; const loc = INDIAN_LOCATIONS.find(l => l.state === state); updateSettings({ selectedState: state, selectedCity: loc?.cities[0] || '' }); }} className="w-full bg-white/10 rounded-lg px-3 py-2 glass-text text-sm outline-none appearance-none">{INDIAN_LOCATIONS.map(l => <option key={l.state} value={l.state} className="bg-gray-800 text-white">{l.state}</option>)}</select><label className="glass-text text-xs block">City</label><select value={settings.selectedCity} onChange={e => updateSettings({ selectedCity: e.target.value })} className="w-full bg-white/10 rounded-lg px-3 py-2 glass-text text-sm outline-none appearance-none">{cities.map(c => <option key={c} value={c} className="bg-gray-800 text-white">{c}</option>)}</select></Section>
    <Section id="sync" section={section} setSection={setSection} title="Sync & Config" icon={<RefreshCw className="w-4 h-4" />}><Slider label="Sync Interval (minutes)" value={settings.syncInterval} min={5} max={120} step={5} onChange={v => updateSettings({ syncInterval: v })} /><button onClick={handleSyncNow} className="w-full glass-panel py-2 flex items-center justify-center gap-2 tap-scale"><RefreshCw className="w-4 h-4 glass-text-subtle" /><span className="glass-text text-xs">Sync Now</span></button><div className="grid grid-cols-2 gap-2"><button onClick={handleExport} className="glass-panel py-2 flex items-center justify-center gap-2 tap-scale"><Download className="w-4 h-4 glass-text-subtle" /><span className="glass-text text-xs">Export Config</span></button><button onClick={() => importRef.current?.click()} className="glass-panel py-2 flex items-center justify-center gap-2 tap-scale"><Upload className="w-4 h-4 glass-text-subtle" /><span className="glass-text text-xs">Import Config</span></button></div><input ref={importRef} type="file" accept="application/json,.json" className="hidden" onChange={handleImport} /><button onClick={clearSearchHistory} className="w-full glass-panel py-2 flex items-center justify-center gap-2 tap-scale"><Trash2 className="w-4 h-4 glass-text-subtle" /><span className="glass-text text-xs">Clear Search History</span></button>{status && <p className="glass-text-subtle text-[11px] text-center">{status}</p>}</Section>
    <Section id="glass-style" section={section} setSection={setSection} title="Glass Style" icon={<Palette className="w-4 h-4" />}><div className="grid grid-cols-2 gap-2">{GLASS_STYLES.map(s => <button key={s.id} onClick={() => applyGlassStyle(s.id)} className={`p-3 rounded-xl text-left transition-all tap-scale ${settings.glassStyle === s.id ? 'bg-white/25 border border-white/40' : 'bg-white/8 border border-white/10'}`}><div className="glass-text text-xs font-medium">{s.name}</div><div className="glass-text-subtle text-[10px] mt-0.5">{s.desc}</div></button>)}</div></Section>
    <Section id="appearance" section={section} setSection={setSection} title="Appearance"><Slider label="Blur Strength" value={settings.blurStrength} min={0} max={50} step={1} onChange={v => updateSettings({ blurStrength: v })} /><Slider label="Glass Opacity" value={settings.glassOpacity} min={0} max={0.5} step={0.01} onChange={v => updateSettings({ glassOpacity: v })} /><Slider label="Border Thickness" value={settings.borderThickness} min={0} max={5} step={0.5} onChange={v => updateSettings({ borderThickness: v })} /><Slider label="Border Opacity" value={settings.borderOpacity} min={0} max={1} step={0.05} onChange={v => updateSettings({ borderOpacity: v })} /><Slider label="Corner Radius" value={settings.cornerRadius} min={0} max={40} step={1} onChange={v => updateSettings({ cornerRadius: v })} /><Slider label="Icon Size" value={settings.iconSize} min={24} max={64} step={2} onChange={v => updateSettings({ iconSize: v })} /><Slider label="Layout Spacing" value={settings.layoutSpacing} min={4} max={32} step={2} onChange={v => updateSettings({ layoutSpacing: v })} /></Section>
    <Section id="sections" section={section} setSection={setSection} title="Sections" icon={<Eye className="w-4 h-4" />}><Toggle label="Weather Widget" checked={settings.showWeather} onChange={v => updateSettings({ showWeather: v })} /><Toggle label="News Feed" checked={settings.showNews} onChange={v => updateSettings({ showNews: v })} /><Toggle label="Shortcut Names" checked={settings.showBookmarkNames} onChange={v => updateSettings({ showBookmarkNames: v })} /></Section>
    <Section id="news-prefs" section={section} setSection={setSection} title="News Preferences" icon={<Newspaper className="w-4 h-4" />}>{NEWS_GENRES.map(genre => { const active = (settings.newsGenres || ['trending']).includes(genre.id); return <Toggle key={genre.id} label={genre.label} checked={active} onChange={() => { const current = settings.newsGenres || ['trending']; let next: NewsGenre[] = active ? current.filter(g => g !== genre.id) : [...current, genre.id]; if (next.length === 0) next = ['trending']; updateSettings({ newsGenres: next }); }} />; })}</Section>
    <Section id="wallpaper" section={section} setSection={setSection} title="Wallpaper"><div className="grid grid-cols-4 gap-2">{WALLPAPERS.map(w => <button key={w.name} onClick={() => updateSettings({ wallpaper: w.src, customWallpaper: null })} className={`w-full aspect-[16/10] rounded-xl overflow-hidden border-2 transition-all tap-scale ${settings.wallpaper === w.src ? 'border-white/60 scale-105' : 'border-transparent'}`}><img src={w.src} alt={w.name} className="w-full h-full object-cover" /></button>)}</div><button onClick={() => fileRef.current?.click()} className="mt-2 w-full glass-panel py-2 flex items-center justify-center gap-2 tap-scale"><Image className="w-4 h-4 glass-text-subtle" /><span className="glass-text text-xs">Upload Custom</span></button><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={handleUpload} /></Section>
  </div></div></div>}</>;
}
